#服务提供者端口配置
server:
  port: 8762

#服务间调用需要根据此名称来调用
spring:
  application:
    name: use-service

#eureka-client服务注册中心配置
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/