#ribbon服务消费者端口配置
server:
  port: 8764

#服务间调用需要根据此名称来调用
spring:
  application:
    name: ribbon-service

#eureka-client:ribbon服务消费者连接注册中心配置
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/